### ISSUE TITLE
Bug de Saltar + shift + menu de pausa

### ISSUE THREAD

**Issue by Pach3co5** [iAmKappy/MinecraftCS#4]
Al hacer Saltar + shift + menu de pausa podes irte al cielo infinitamente y hay un punto donde si te paras y saltas normal se te pone todo negro la pantalla

Video demostrativo:

https://user-images.githubusercontent.com/47259346/152268296-75603d0c-2a0b-4b98-beea-c6a8a5e2df15.mp4

**Comment by iAmKappy** [comment]
✅Solucionado para la próxima versión 🔍 ¡Gracias por reportar!👌
