### ISSUE TITLE
Bug de la losa

### ISSUE THREAD

**Issue by Pach3co5** [iAmKappy/MinecraftCS#5]
Puedes atraversa la losa cuando deschifteas pero si saltas y sales ya no puedes saltar otra vez

Video demostrativo:

https://user-images.githubusercontent.com/47259346/152269512-aea9b39e-938a-47e7-b092-313bb6731382.mp4

**Comment by iAmKappy** [comment]
✅ Ya había sido reportado arreglado para la próxima versión 👌
